{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "example2.serviceAccountName" . }}
  labels:
{{ include "example2.labels" . | indent 4 }}
{{- end -}}
